name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - run: dotnet test
    - run: dotnet run -p src/Fslisp.Driver -- -test lispboot/test
    - run: dotnet build --configuration Release
