name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - run: make test
    - run: make test-lispboot
    - run: make build
